### ISSUE TITLE
Default Snap! code not working on macOS

### ISSUE THREAD

**Issue by adrian-hintze** [adrian-hintze/Snapp#12]
There is some issue that causes Snap! to crash when running on Mac OS. The crash occurs during the code handling the retina display.

It's probably related to the outdated version of NW.js.

**Comment by Rydion** [comment]
Check again if the original code works now that NW.js has been updated to the latest version.

**Comment by adrian-hintze** [comment]
Not happening anymore with the newest NW.js version
