### ISSUE TITLE
Unknow client error

### ISSUE THREAD

**Issue by PCprof** [adrian-hintze/Snapp#22]
Hello. I tried to build a snap project but I only get this error message : unknow client error. Please reload the page and try again. My project is 2507Ko, I choose 1024x728 or 800x600, with ou without code access and for Windows 32 bits.
I'll try again later.
![gib](https://user-images.githubusercontent.com/41064725/42514160-04642870-8459-11e8-8cc7-8f74d68c2f20.jpg)

**Comment by Rydion** [comment]
Hi @PCprof, I'll have a look into it this week. Would it be possible for you to share the Snap! project you were using?

**Comment by PCprof** [comment]
Hello, I've done it, it's name "6 Fleur et graines"

**Comment by Rydion** [comment]
Hi, I've tried opening the project through Snap but it does not seem to be able to find it. Is your username on Snap "pcprof" and the project name exactly "6 Fleur et graines"? If you could just attach the XML here or send it to my email it would probably be easier.

**Comment by Hearterx** [comment]
Idem! I can't make my app
:c

**Comment by Rydion** [comment]
Hi, a fix is ready. I'm having some trouble with the hosting, as soon as that is fixed (Monday hopefully) this issue should be solved. thank you for your patience.

**Comment by Rydion** [comment]
@Hearterx Could you share your project XML file?

**Comment by adrian-hintze** [comment]
Closing as this should be fixed and I'm getting no feedback.
