### ISSUE TITLE
No sound?

### ISSUE THREAD

**Issue by bromagosa** [adrian-hintze/Snapp#3]
Hi @Rydion!

Forwarded from Scratch forum user by @brianharvey:

> I have to make programme to help my students (7 years old) to play some sounds when they clic on pictures.
> Scrach is to slow : there is almost 1s between the clic and the sound.
> Snap is faster.
> But I need to do it without internet. So I made a standalone executable here : http://snapp.citilab.eu/
> I just put a sound “cat” from the library in the sprite and made it play on clic.
> It is working very fast in the interface but there is no sound when the executable is working…

https://scratch.mit.edu/discuss/post/2055142/

**Comment by Rydion** [comment]
Hi, so this is a tricky one!

If you build any project with Snapp! then extract it and open it with a browser the cat sound plays just fine. The problem seems to be related to Node.js. Do you know by any chance if the sound is an mp3 file?

If not I'll test it out myself, but it would save me some time.

**Comment by bromagosa** [comment]
That's funny. I actually have the same issue in Snap4Arduino: https://github.com/edutec/Snap4Arduino/issues/30

I've been investigating a bit, and I found out it's a license issue. libffmpeg is proprietary and can't be redistributed without proper license (meaning we can't distribute it either!).

In any case, here's the thread that explains it: https://github.com/nwjs/nw.js/issues/4492#issuecomment-192047570

So I guess this issue can't be fixed unless libffmpeg is liberated... :(

**Comment by Rydion** [comment]
Hi, thank you for investigating the issue! I had read something about it but hadn't been able to delve deeper into it. I'll leave this issue open hoping that maybe one day we can use the library freely.

**Comment by JSJBDEV** [comment]
@bromagosa @Rydion I HAVE A SOLUTION (i had this problem as you can see in issue #6 ) so I have solved one of the 3 things by myself.

to make sound work you should convert the sound file to a .ogg as snap! supports it and it is a "free open container format" once i had recompiled my project (and avast decided it was ok) the music started working.
all the best!
~JSJBdev

**Comment by bromagosa** [comment]
Yep, that's exactly [the conclusion I reached too](https://github.com/edutec/Snap4Arduino/issues/30#issuecomment-231022781).

Glad you found a solution to your issue! :)

**Comment by Rydion** [comment]
@bromagosa 

I don't know if this is still relevant to you, but the mp3 patent is about to expire (or it has already, I'm not completely sure). This means the relevant code will probably be included in future versions of NW.js.

**Comment by bromagosa** [comment]
Yep! I read about this just about a week ago, it was about time! :)

**Comment by Rydion** [comment]
NW.js now should be able to play MP3 files by default. Check for next version.

**Comment by adrian-hintze** [comment]
MP3 now supported by default in NW.js
