### ISSUE TITLE
Snapp standalone creator incompatibility with Snap 5

### ISSUE THREAD

**Issue by MaestroCaldwell** [adrian-hintze/Snapp#30]
If you have coded recently with the "go to front" block in Snap 4.2, the Snapp standalone creator has an issue with the newly changed/updated "go to front/back layer" block from Snap 5. The "go to front" block is no longer used in 5.0, so the new blocks are automatically changed.
I get "a custom block definition is missing," and the rest of my code fails to run correctly as a result (in the exe, not in Snap 5).
Since I can no longer use the old block, in the meantime my workaround is to use the older offline Snap 4.2 to export my xml files.
Is there a way to update Snapp to fix this? I enjoy using the cloud save feature.
![Image12](https://user-images.githubusercontent.com/52303624/60548363-c2fff700-9cd6-11e9-8d40-09ddcf21483c.png)

**Comment by adrian-hintze** [comment]
Hi @MaestroCaldwell,

I try to keep Snapp updated to use the latest version of Snap. I've been wanting to update for a while now, but I need to find time to finalise some things and test.

Do expect an update soon.

**Comment by MaestroCaldwell** [comment]
Awesome, thanks @adrian-hintze. 
I appreciate all the work you do, and my students appreciate you too.

**Comment by adrian-hintze** [comment]
Hi @MaestroCaldwell,

Just a quick heads up. Not sure if you've already seen it, but Snapp has been using the Snap's v5 for a couple of weeks now. 

Cheers
