### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by biran4454** [adrian-hintze/Snapp#31]
I get a ' 502 bad gateway' error when I try to load snapp.citilab.edu.

**Comment by bromagosa** [comment]
That's because the URL is wrong ;)

It should be .eu, not .edu

(also, server was down for a bit)

**Comment by biran4454** [comment]
@bromagosa 
OK, but now I get a thing saying 

> 'Access through untrusted domain' 

>'Please contact your administrator. If you are an administrator, edit the "trusted_domains" setting in config/config.php like the example in config.sample.php.
Further information how to configure this can be found in the documentation.'#
Is that what you meant by the server being down?

**Comment by bromagosa** [comment]
Hmm, are you trying to access http://snapp.citilab.eu/?

It works fine for me:

![image](https://user-images.githubusercontent.com/1016697/64148256-274c4d80-ce23-11e9-8eba-15eae6cb3924.png)

**Comment by biran4454** [comment]
OK, I think I was going to
>https://snapp.citilab.eu

not

>http://snapp.citilab.eu
